package:
  name: scitools
  version: "0.9.0"

source:
  git_url: https://github.com/hplgit/scitools.git

build:
  number: 0

requirements:
  build:
    - python
    - numpy
    - matplotlib
    - py-gnuplot

  run:
    - python
    - numpy
    - matplotlib
    - py-gnuplot

test:
  # Python imports
  imports:
    - scitools.easyviz
    - scitools

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://scitools.googlecode.com
  license: BSD License
  summary: 'Python library for scientific computing'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
